### ISSUE TITLE
貌似不兼容uniapp的的一些属性,比如rpx,以及全局属性

### ISSUE THREAD

**Issue by fendo8888** [icebreaker-template/uni-app-vue2-tailwind-hbuilder-template#2]
貌似不兼容uniapp的的一些属性,比如rpx,使用rpx的话,貌似没有被解析,直接显示出来了
![image](https://user-images.githubusercontent.com/22114481/192668885-83f40294-cf35-4bcb-b0ff-0cb7d4254442.png)

还有就是比如uniapp设置全局页面背景色

`
	page{
		width: 100%;
		height: 100%;
		background-color: red;
	}
`

不管是在app.vue还是当前页面里使用都不生效，不知道啥情况

**Comment by sonofmagic** [comment]
可能是 `hot reload` 失效了，你把微信开发者工具的热重载关了试试呢

**Comment by fendo8888** [comment]
> 可能是 `hot reload` 失效了，你把微信开发者工具的热重载关了试试呢

我这是H5

**Comment by sonofmagic** [comment]
那h5本来就没有 `page` 这个元素 和 `rpx` 这个单位，他们都是小程序特有的，不要混淆了

你h5 应该用 `html` , `body` 标签，自适应应该用 `rem`/`vw` 这样的 `css` 单位。

**Comment by fendo8888** [comment]
> 那h5本来就没有 `page` 这个元素 和 `rpx` 这个单位，他们都是小程序特有的，不要混淆了
> 
> 你h5 应该用 `html` , `body` 标签，自适应应该用 `rem`/`vw` 这样的 `css` 单位。

怎么可能，uniapp中多端都支持rpx单位，他会自动转换

https://uniapp.dcloud.net.cn/tutorial/syntax-css.html#%E5%B0%BA%E5%AF%B8%E5%8D%95%E4%BD%8D

page这是我在uniapp项目里使用是正常的

https://blog.csdn.net/weixin_39793790/article/details/106472680

**Comment by sonofmagic** [comment]
我懂了， `uni-app` 有有 `postcss` 插件，会针对 `h5` 环境的元素，做特殊处理，帮你把这些单位给转化了 。

而在这个模板里，这些转化失效了。

这个需要我新创建一个 `uni-app` 的项目看看规则。

**Comment by fendo8888** [comment]
> 我懂了， `uni-app` 有有 `postcss` 插件，会针对 `h5` 环境的元素，做特殊处理，帮你把这些单位给转化了 。
> 
> 而在这个模板里，这些转化失效了。
> 
> 这个需要我新创建一个 `uni-app` 的项目看看规则。

应该是的

**Comment by sonofmagic** [comment]
我看了一下源码，是 `@dcloudio/vue-cli-plugin-uni/packages/postcss` 做的多平台的兼容性转化，我把它手动引入了进来。

你可以获取一下，新的模板代码再试试。我试了一下 `h5` 和 微信小程序，看上去是生效了。

**Comment by fendo8888** [comment]
> 我看了一下源码，是 `@dcloudio/vue-cli-plugin-uni/packages/postcss` 做的多平台的兼容性转化，我把它手动引入了进来。
> 
> 你可以获取一下，新的模板代码再试试。我试了一下 `h5` 和 微信小程序，看上去是生效了。

好的，我试下

**Comment by fendo8888** [comment]
可以了，谢谢
