### ISSUE TITLE
抛出编译异常

### ISSUE THREAD

**Issue by mvplove123** [icebreaker-template/uni-app-vue2-tailwind-hbuilder-template#3]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/8490158/194579578-d37733df-98a4-4bae-95c4-ebcc9a8cf784.png">

直接用的这个模板，在H5可以展示，在小程序上不可以，编译异常

**Comment by sonofmagic** [comment]
我重新获取了这个 `clone` 模板，然后先在项目目录下，执行 `yarn` 安装，然后使用 `hbuilderx` 打开，运行到小程序模拟器，微信小程序，运行正常，没有出现你这样的问题呢。
你能告诉我你的执行步骤吗？

**Comment by mvplove123** [comment]
> 我重新获取了这个 `clone` 模板，然后先在项目目录下，执行 `yarn` 安装，然后使用 `hbuilderx` 打开，运行到小程序模拟器，微信小程序，运行正常，没有出现你这样的问题呢。 你能告诉我你的执行步骤吗？

模板clone时，初始在小程序运行没有问题，后来我编写页面代码后，在小程序运行时报的错，提示文件编译有问题

**Comment by sonofmagic** [comment]
奇怪了，我也在 `hbuilderx ` 运行小程序的时候，在 `hbuilderx ` 编写页面代码，添加 `<text class="text-[44px] my-[222px] ml-0.5"></text>` ，保存之后也生效了呢。你先尝试升级 `weapp-tailwindcss-webpack-plugin` 到最新版本。
然后还是有问题的话，不知可否提供一个能复现这个 `issue` 的 `demo` 给我。

而且看你的报错，你是 `MacOS` ，我在 `Windows10/11` 上测试是没问题的，`Mac` 的话，到时候我借朋友的跑跑。

**Comment by imaxing** [comment]
@sonofmagic @mvplove123 
hi, 经测试在我的macos上运行没有问题 以下是我的环境信息:

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/26427785/194688170-ed21425f-2625-4f8e-a075-74ad72e3446c.png">


```bash
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 518.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6.1
```

控制台输入命令获取环境信息可以更快帮助作者找到问题:
```bash
npx envinfo --system --npmPackages vitepress --binaries --browsers
```

**Comment by mvplove123** [comment]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/8490158/194689164-3e339321-8023-4a89-ad4e-0ac2fe66d54a.png">

这个是我的环境
<img width="813" alt="image" src="https://user-images.githubusercontent.com/8490158/194689230-3f72ef56-ea60-45d9-ab18-85e145202648.png">

**Comment by mvplove123** [comment]
<img width="892" alt="image" src="https://user-images.githubusercontent.com/8490158/194689325-a6dc08b7-4257-47ff-8155-8660c75c64c5.png">

当前weapp-tailwindcss-webpack-plugin 的版本如上

**Comment by sonofmagic** [comment]
经过交流是 `vue.config.js` 中配置的问题， close。
