### ISSUE TITLE
小程序中，button的transform失效

### ISSUE THREAD

**Issue by freshbird** [icebreaker-template/uni-app-vue2-tailwind-hbuilder-template#7]
我找到原因了，生成的main.wxss里对tailwind的transform的定义是这样的：
`view,::before,::after{
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  --tw-skew-y: 0;
  --tw-scale-x: 1;
  --tw-scale-y: 1;
  --tw-transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  --tw-border-opacity: 1;
  border-color: rgba(229, 231, 235, var(--tw-border-opacity));
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
  --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
  --tw-ring-offset-width: 0px;
  --tw-ring-offset-color: #fff;
  --tw-ring-color: rgba(59, 130, 246, 0.5);
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
  box-sizing: border-box;
  border-width: 0;
  border-style: solid;
  border-color: currentColor;
}`
导致transform只对view起作用，如果把`view,::before,::after{`改成`view,button,::before,::after{`就可以实现button的transform操作。
不知道我的理解对不对。

**Comment by freshbird** [comment]
在H5端生成的类名是：`*, ::before, **::after`，但以*作为类名在小程序里是会报错的，只能用view，这就导致了只能是`view,::before,::after`，并不包含button，导致transform失效

**Comment by freshbird** [comment]
我是想实现一个button在点击时的平移效果，才发现这个问题

**Comment by sonofmagic** [comment]
是的呢，的确就是这个原因，导致偏移没有生效  
我这个插件 [weapp-tailwindcss-webpack-plugin](https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin) 有一个 `cssPreflightRange` 配置项，可以更改这个选择器，到全局上，链接在
https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin#csspreflightrange

你看看是否可以满足这个需求？ 如果不行，我可能要扩展这个选项，允许用户完全自定义这个 `preflight` 变量注入选择器。

**Comment by sonofmagic** [comment]
当然，假如不更改的话，建议给 button 套个view, 这种操作都在 view 上做，哈哈

**Comment by freshbird** [comment]
> 当然，假如不更改的话，建议给 button 套个view, 这种操作都在 view 上做，哈哈

套个view固然可以，但我希望能不需要做特殊处理，尽量符合tailwind的原生使用习惯，大家在使用的时候无感知，这就最好了，老哥有微信或者QQ吗？我对你这项目挺感兴趣的，可以一起讨论，让它越来越好

**Comment by freshbird** [comment]
> 是的呢，的确就是这个原因，导致偏移没有生效 我这个插件 [weapp-tailwindcss-webpack-plugin](https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin) 有一个 `cssPreflightRange` 配置项，可以更改这个选择器，到全局上，链接在 https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin#csspreflightrange
> 
> 你看看是否可以满足这个需求？ 如果不行，我可能要扩展这个选项，允许用户完全自定义这个 `preflight` 变量注入选择器。
`添加cssPreflightRange:"all"`后button可以平移了

**Comment by freshbird** [comment]
> 是的呢，的确就是这个原因，导致偏移没有生效 我这个插件 [weapp-tailwindcss-webpack-plugin](https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin) 有一个 `cssPreflightRange` 配置项，可以更改这个选择器，到全局上，链接在 https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin#csspreflightrange
> 
> 你看看是否可以满足这个需求？ 如果不行，我可能要扩展这个选项，允许用户完全自定义这个 `preflight` 变量注入选择器。

添加`cssPreflightRange:"all"`后可以平移了，问题解决

**Comment by sonofmagic** [comment]
有的，就在我的 https://github.com/sonofmagic 首页，扫个码就加上了。
